permalink: pretty

prose:
  rooturl: "_posts"
  metadata: 
    _posts/people: |
      # ABOUT ME
      title: Firstname Lastname
      class: Senior
      email: email@site.com
      committees:
      - name: Committee One
        link: /committees/#committee_one
      - name: Committee Two
        link: /committees/#committee_two

      # SITE STUFF YOU CAN EDIT
      published: true
      permalink: /people/firstname-lastname/

      # SITE STUFF YOU SHOULDN'T EDIT
      layout: people-single
      category: people
    _posts/notes: |
      # MEETING OR EVENT INFO
      title: Meeting or Event Title
      notetaker: Firstname Lastname

      # SITE STUFF YOU CAN EDIT
      published: true

      # SITE STUFF YOU SHOULDN'T EDIT
      layout: notes-single
      category: notes