permalink: /:categories/:title/
exclude:
- .gitignore
- README.md
- _config.yml

prose:
  rooturl: "_posts"
  metadata: 
    _posts/people: |
      published: false
      category: people
      layout: people-single
      title: Firstname Lastname
      class: Senior
      email: email@cooper.edu
      committees:
      - name: Committee Name
        link: /committees/#committee_hash
      - name: Another Committee Name
        link: /committees/#another_committee_hash